name: Build Image and Push Export

on: 
  push:
  workflow_dispatch:

jobs:
  pelican-export:
    name: Build and Push Pelican Export Image
    uses: uc-cdis/.github/.github/workflows/image_build_push_native.yaml@master
    with:
      DOCKERFILE_LOCATION: "./export.Dockerfile"
      OVERRIDE_REPO_NAME: "pelican-export"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
